[package]
name = "email-sanitizer"
version = "0.2.0+sprint1"
edition = "2024"

[dependencies]
actix-web = "4.4.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
chrono = "0.4.40"
serde_json = "1.0.140"

[dev-dependencies]
husky = "0.3.0"
